### ISSUE TITLE
bug: 2.12.0 breaks tagged builds

### ISSUE THREAD

**Issue by wheresrhys** [nickmerwin/node-coveralls#159]
https://github.com/nickmerwin/node-coveralls/releases/tag/2.12.0 breaks CI builds triggered by tags.

```
fs.js:634
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/ubuntu/n-ui/.git/refs/heads/master'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at detectLocalGit (/home/ubuntu/n-ui/node_modules/coveralls/lib/detectLocalGit.js:26:19)
    at getBaseOptions (/home/ubuntu/n-ui/node_modules/coveralls/lib/getOptions.js:105:43)
    at Object.getOptions (/home/ubuntu/n-ui/node_modules/coveralls/lib/getOptions.js:165:3)
    at handleInput (/home/ubuntu/n-ui/node_modules/coveralls/lib/handleInput.js:7:8)
    at Socket.<anonymous> (/home/ubuntu/n-ui/node_modules/coveralls/bin/coveralls.js:16:5)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
make: *** [test-server] Error 1
```

In circleci https://circleci.com/gh/Financial-Times/n-ui/4163

**Comment by nickmerwin** [comment]
Hi @wheresrhys this seems to be a CircleCI specific issue -- when running on Travis it checks out the tagged branch and writes the file `.git/refs/heads/<tag>` . Could you re-run on Circle and let me know what is present in that directory?
