### ISSUE TITLE
Not a valid object name error when upgrading from v3.0.9 to v3.0.11

### ISSUE THREAD

**Issue by nlordell** [nickmerwin/node-coveralls#280]
The following error appears when bumping `coveralls` from `v3.0.9` to `v3.0.11`:
```
[error] "2020-03-20T02:45:46.583Z"  'error from getOptions'
/home/travis/build/gnosis/dex-contracts/node_modules/coveralls/bin/coveralls.js:19
      throw err;
      ^

Error: Command failed: git cat-file -p cd747d4d62972cd3c584752636c9789c7ed4a63e
fatal: Not a valid object name cd747d4d62972cd3c584752636c9789c7ed4a63e

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
```

**Comment by taozhi8833998** [comment]
the same issue + 1

**Comment by amitksingh1490** [comment]
+1

**Comment by ericmorand** [comment]
Wow. A breaking change on a patch release. How is that even possible.

Thanks for the heads-up though, I'll downgrade coveralls too.

**Comment by nickmerwin** [comment]
Hi all, I've reverted the change that likely caused this issue:

https://github.com/nickmerwin/node-coveralls/blame/21f476c8502e180a7a1e67035cba57616fecc5be/lib/getOptions.js#L29

And released a new version.

**Comment by nlordell** [comment]
Thanks! Worked like a charm.
