### ISSUE TITLE
Jenkins error - fatal: Not a valid object name

### ISSUE THREAD

**Issue by afinetooth** [nickmerwin/node-coveralls#304]
Submitting on behalf of a new user with repo:
https://coveralls.io/github/germyjen/emrap-corependium

Issue reported as follows:

---------- Forwarded message ---------
From: Sysadmin <sysadmin@silverorange.com>
Date: Wed, Jun 10, 2020 at 10:02 AM
Subject: Re: Can't get coveralls to work with Jenkins CI
To: James Kessler <james@coveralls.io>
Cc: support <support@coveralls.io>

> When implemented in Jenkins we do still run into the same git error as before:
> 
> ```
> [error] "2020-06-04T00:31:39.904Z"  'error from getOptions'/var/lib/jenkins/workspace/emrap-corependium-PR-484/client/node_modules/coveralls/bin/coveralls.js:19      
>             throw err;      
>             ^
> Error: Command failed: git cat-file -p 115e0c6233e17cae29d5fd19add99627570b85fd
> fatal: Not a valid object name 115e0c6233e17cae29d5fd19add99627570b85fd    
>   at ChildProcess.exithandler (child_process.js:294:12)    
>   at ChildProcess.emit (events.js:198:13)    
>   at maybeClose (internal/child_process.js:982:16)    
>   at Socket.stream.socket.on (internal/child_process.js:389:11)    
>   at Socket.emit (events.js:198:13)    
>   at Pipe._handle.close (net.js:607:12)
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> script returned exit code 1
> ```
> 
> Do you have any idea why this git error would be occurring when running coveralls in CI pipelines in Jenkins?
> 
> Thanks!
> Jayme

**Comment by afinetooth** [comment]
Two (2) related issues here:

1. https://github.com/nickmerwin/node-coveralls/issues/80
2. https://github.com/nickmerwin/node-coveralls/issues/280

(2) indicates an upgrade (or downgrade) might resolve. Have suggested and asked the user their current version.

**Comment by jaymefSO** [comment]
The version in use is the latest 3.1.0 

"coveralls": "^3.1.0",
