### ISSUE TITLE
Invalid reporter

### ISSUE THREAD

**Issue by theofidry** [nickmerwin/node-coveralls#79]
Hi,

I'm trying to use Coverballs with Instanbul and Moch as detailed [here](https://github.com/cainus/node-coveralls).

The command they give is:

``` bash
istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
```

Since I've written my tests in a `test` directory and not `spec`I just changed that. Still, it's not working and I don't get why, it seems to come from the reporter:

``` bash
istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R test/**/*-test.js && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
=============================================================================
Writing coverage object [/path/to/project/coverage/coverage.json]
Writing coverage reports at [/path/to/project/coverage]
=============================================================================

=============================== Coverage summary ===============================
Statements   : 34.98% ( 78/223 )
Branches     : 1.49% ( 1/67 )
Functions    : 13.04% ( 9/69 )
Lines        : 34.98% ( 78/223 )
================================================================================
/path/to/project/node_modules/mocha/lib/mocha.js:149
    if (!_reporter) throw new Error('invalid reporter "' + reporter + '"');
                          ^
Error: invalid reporter "test/middleware/dbf-upload-test.js"
    at Mocha.reporter (/path/to/project/node_modules/mocha/lib/mocha.js:149:27)
    at Object.<anonymous> (/path/to/project/node_modules/mocha/bin/_mocha:214:7)
    at Module._compile (module.js:460:26)
    at Module._extensions..js (module.js:478:10)
    at Object.Module._extensions..js (/usr/local/lib/node_modules/istanbul/lib/hook.js:102:13)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at runFn (/usr/local/lib/node_modules/istanbul/lib/command/common/run-with-cover.js:116:16)
    at /usr/local/lib/node_modules/istanbul/lib/command/common/run-with-cover.js:241:17
    at /usr/local/lib/node_modules/istanbul/lib/util/file-matcher.js:68:16
    at /usr/local/lib/node_modules/istanbul/node_modules/async/lib/async.js:254:17
    at done (/usr/local/lib/node_modules/istanbul/node_modules/async/lib/async.js:135:19)
    at /usr/local/lib/node_modules/istanbul/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/istanbul/node_modules/async/lib/async.js:251:21
    at LOOP (fs.js:1478:14)
    at process._tickCallback (node.js:355:11)
```

**Comment by mathiasrw** [comment]
The `-R` try to setup a reporter. Please remove that part.
